
services:
  postgres:
    image: postgres:17-alpine3.21
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      - POSTGRES_USER=kadera
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build: 
      context: .
      dockerfile: Dockerfile 
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports: 
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://kadera:secret@postgres:5432/simple_bank?sslmode=disable
